### ISSUE TITLE
Why OpenGL 4.6 ?

### ISSUE THREAD

**Issue by Lecrapouille** [cucumberbolts/Chess#3]
Hello, just a question when reading your README: why such a recent OpenGL is required for drawing a chessboard ? Cannot be reduced to OpenGL 3.3 ?

Thanks!

**Comment by cucumberbolts** [comment]
One of the reasons I used OpenGL was so I could learn the basics of software rendering and I thought using the latest version would be the best choice. I suppose you have a good point though--it's just a simple chessboard that doesn't require cutting edge features. I'll consider moving to an older version if it means support for more platforms.

**Comment by Lecrapouille** [comment]
What about OpenGL ES for web compatibility (`cd build; emcmake cmake ..; emmake make`) ?

**Comment by cucumberbolts** [comment]
WebAssembly and OpenGL ES is beyond the scope of what I had originally intended, though if you know how to implement this, I would be more than happy to accept any pull requests!
